# Generated by Django 4.0.1 on 2022-11-30 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('garage_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('area', models.CharField(max_length=200)),
                ('available', models.CharField(default='1', max_length=2)),
                ('space', models.CharField(max_length=200)),
                ('hourlyprice', models.FloatField()),
                ('monthlyprice', models.FloatField()),
                ('dailyprice', models.FloatField()),
                ('upload', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('type', models.CharField(choices=[('Car', 'Car'), ('Mini Bus', 'Mini Bus'), ('Bike', 'Bike'), ('Bicycle', 'Bicycle'), ('Bus', 'Bus'), ('Truck', 'Truck')], default='choose one', max_length=30)),
                ('vehicle_num', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('vehicle_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomepageApp.vehicleowner')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(max_length=50)),
                ('reviewed', models.CharField(max_length=50)),
                ('statement', models.TextField(max_length=250)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.CharField(choices=[('Hourly', 'Hourly'), ('Monthly', 'Monthly'), ('Daily', 'Daily')], default='choose one', max_length=30)),
                ('rental_date', models.DateTimeField(auto_now_add=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomepageApp.garage')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomepageApp.vehicleowner')),
            ],
        ),
        migrations.CreateModel(
            name='GarageOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='garage',
            name='garage_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomepageApp.garageowner'),
        ),
    ]
