# Generated by Django 4.0.1 on 2022-11-22 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomepageApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cust',
        ),
    ]
