# Generated by Django 4.0.1 on 2022-11-22 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HomepageApp', '0002_delete_cust'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garageowner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='garageowner',
            name='username',
        ),
        migrations.RemoveField(
            model_name='vehicleowner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vehicleowner',
            name='username',
        ),
        migrations.AlterField(
            model_name='garageowner',
            name='users',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicleowner',
            name='users',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
